spring:
  application:
    name : activityservice
  data:
    mongodb:
      url: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
