spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-micro-user
    username: postgres
    password: Ashish@853
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081